theme: osuny
_merge: deep
params:
  plausible: bonnesnotes.org
  search:
    active: true
  posts:
    index:
      layout: grid
  components:
    lightbox:
      disabled: true
  debug:
      productionUrl: "https://www.bonnesnotes.org"