theme: osuny-hugo-theme-aaa

## LANGUAGE
defaultContentLanguage: fr
defaultContentLanguageInSubdir: true
languageCode: fr
languages:
  en:
    weight: 2
  fr:
    weight: 1

## ADVANCED
paginate: 18
enableRobotsTXT: true

## MODULE
module:
  _merge: deep

## PARAMS
params:
  _merge: deep
  cookie_banner:
    enable: false
